spring.datasource.url=jdbc:postgresql://localhost:5432/parkvue_cric_info
spring.datasource.username=cric_user
spring.datasource.password=cric_password
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
