spring.datasource.url=jdbc:postgresql://localhost:5432/parkvue_cric_info
spring.datasource.username=cric_user
spring.datasource.password=cric_password
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
